/**
 * Place action types
 */
export const NEW_PLACE_PIN_ADDED = 'NEW_PLACE_PIN_ADDED';
export const NEW_PLACE_CANCELED = 'NEW_PLACE_CANCELED';
export const NEW_PLACE_SUBMITED = 'NEW_PLACE_SUBMITED';
export const PLACE_EDITED = 'PLACE_EDITED';
export const PLACE_REMOVED = 'PLACE_REMOVED';
export const PLACE_FORM_CLOSED = 'PLACE_FORM_CLOSED';
export const PLACE_EDITING = 'PLACE_EDITING';
export const PLACE_REMOVE_CONFIRMATION = 'PLACE_REMOVE_CONFIRMATION';
export const PLACE_REMOVE_CONFIRMED = 'PLACE_REMOVE_CONFIRMED';
export const PLACE_REMOVE_CANCELED = 'PLACE_REMOVE_CANCELED';
export const OPEN_CONFIRMATION_MODAL = 'OPEN_CONFIRMATION_MODAL';
export const CLOSE_CONFIRMATION_MODAL = 'CLOSE_CONFIRMATION_MODAL';
