/**
 * Location actions
 */
export const SEARCH_INPUT_CHANGED = 'SEARCH_INPUT_CHANGED';
export const SEARCH_API_REQUESTING = 'SEARCH_API_REQUESTING';
export const SEARCH_API_SUCCESS = 'SEARCH_API_SUCCESS';
export const SEARCH_API_FAILURE = 'SEARCH_API_FAILURE';
